[".config/tmux/oh-my-tmux"]
type = "git-repo"
url = "https://github.com/gpakosz/.tmux.git"
refreshPeriod = "168h"

[".config/alacritty/themes"]
type = "git-repo"
url = "https://github.com/alacritty/alacritty-theme"
