
[tools]

node = ['20', '18']
python = ['3', '3.8', '3.11']
ruby = ['3']
go = ['1.22']
java = ['corretto-21', 'corretto-17', 'corretto-11', 'corretto-8']
gradle = ['8', '7', '6']
scala = ['3', '2.13', '2.12']
elixir = ['1.17']
erlang = ['27']
usage = "latest"

[alias.java]
'21' = 'corretto-21'
'17' = 'corretto-17'
'11' = 'corretto-11'
'8' = 'corretto-8'
