#!/usr/bin/env zsh
# vim: set filetype=zsh :

zmodule environment
zmodule input
zmodule run-help
zmodule git
zmodule termtitle
zmodule utility
zmodule zsh-users/zsh-completions --fpath src
zmodule completion
zmodule Aloxaf/fzf-tab
zmodule Freed-Wu/fzf-tab-source
zmodule zdharma-continuum/fast-syntax-highlighting
zmodule zsh-users/zsh-autosuggestions
