
[tools]

node = ['18', '20']
python = ['3']
ruby = ['3']
go = ['prefix:1.20']
java = ['corretto-17', 'corretto-11', 'corretto-8']

[plugins]

node = 'https://github.com/rtx-plugins/rtx-nodejs.git'
python = 'https://github.com/jdxcode/rtx-python'
go = 'https://github.com/kennyp/asdf-golang.git'
java = 'https://github.com/rtx-plugins/rtx-java.git'
ruby = 'https://github.com/rtx-plugins/rtx-ruby.git'

